ktor:
  application:
    modules:
      - com.lilac.identity.ApplicationKt.module
  deployment:
    port: ${PORT}
  development: true

jwt:
  domain: ${DOMAIN}
  issuer: "lilac-identity"
  audience: "lilac-identity"
  realm: "Lilac Identity"
  algorithm: "HS256"
  accessTokenExpInMins: 15
  refreshTokenExpInDays: 30
  emailVerificationExpInMins: 10
  resetPasswordExpInMins: 10
  secret: ${JWT_SECRET}

token:
  secret: ${TOKEN_SECRET}

postgres:
  url: ${DATABASE_URL}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  maximumPoolSize: 10

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD} # Usually SMTP Key
  from: ${MAIL_FROM}